### ISSUE TITLE
hpcviewer spews errors to stdout or stderr on Power9

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#70] opened 2020-02-13 21:46 UTC
If the errors are unavoidable and not of much concern, record them in a log file and don't spew them to the terminal. This can be handled by the wrapper script if the java executable encounters errors before it can set up redirection to a file.

**Comment by laksono** [comment] 2020-02-13 22:53
This issue is a duplicate of issue #47.

There is nothing to worry about the error message. This only happens if we use Eclipse compatibility layer.
Agree, for the quick fix to redirect the standard error.

**Closed** 2020-02-26 23:04 UTC
Labels: bug
