### ISSUE TITLE
hpcviewer view menu disappeared under linux

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#69] opened 2020-02-09 00:30 UTC
I used the view menu to show CCT IDs and to show the experiment.xml file.

When I went looking for it next (after exploring the CCT some), the view menu was gone. See the screenshot below

<img width="914" alt="image" src="https://user-images.githubusercontent.com/3926112/74094094-08707800-4aa1-11ea-9be4-7082e120f6b3.png">

**Comment by laksono** [comment] 2020-02-09 00:54
Which platform did you run? This is important to know if it's from pure Eclipse 3.x (x86) or Eclipse 4.x (ppc64le).

**Comment by jmellorcrummey** [comment] 2020-02-09 02:17
ppcle

**Comment by laksono** [comment] 2020-02-10 17:39
The bug happens because of the condition for the "View" menu. The menu is shown if the number of opened database is greater than zero, otherwise, it's hidden.
This works if we always use a single-window application, but buggy if there are two windows: if one has opened databases while the other has none.
To reproduce the bug:
1. Open a database
1. Open a new window, do NOT open a database in this window
1. The "View" menu of both windows will be hidden.

I think this is an Eclipse limitation that it stores the flag for all application windows.
An alternative solution is by programmatically hide/show the menus, instead of using Eclipse's declarative condition.

**Comment by laksono** [comment] 2020-02-10 19:16
Fixed in commit a5e8946f5a1fbe97d0bb35ab0d6350fa215923a2

**Closed by laksono** 2020-02-10 19:16 UTC
